Repository wiki-viki/wiki-viki, pull requests merged in 2024-06, with the labels that each got.

#2 🎉 Init: 프로젝트 초기 세팅
  .commitlintrc.json
  .eslintrc.json
  .husky/commit-msg
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/apis/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/index.tsx
  src/styles/globals.css
  src/types/index.ts
  src/utils/index.ts
  tailwind.config.ts
Labels: 📦️ Chore

#7 📦️ Chore: 커스텀 색상 및 폰트 변수 설정
  src/components/common/index.ts
  src/pages/_document.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 📦️ Chore

#16 🚑️ Fix: commitlint subject-case 규칙 제거
  .commitlintrc.json
Labels: 🚑️ Fix

#17 📦️ Chore: vercel 배포 및 CICD 구현(Git Actions)
  .github/workflows/git-push.yml
  .github/workflows/perview.yml
  .huskyrc
  build.sh
  package-lock.json
  src/pages/index.tsx
Labels: 📦️ Chore

#15 ✨ Feat: 버튼, 페이지네이션 공통 컴포넌트 구현
  src/components/common/CommonButton.tsx
  src/components/common/Pagination.tsx
  src/components/common/index.ts
  src/pages/test2.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feat

#12 ✨ Feat: 로그인, 회원가입 input 구현
  constants/messages.tsx
  constants/regex.ts
  src/components/Auth/AuthContainer.tsx
  src/components/Auth/AuthInputWithLabel.tsx
  src/components/Auth/AuthSwitchPrompt.tsx
  src/components/Auth/index.ts
  src/components/common/Form/Input.tsx
  src/components/common/Form/Label.tsx
  src/components/common/Form/index.ts
  src/components/common/Pagination.tsx
  src/pages/index.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/types/authFormType.ts
  src/types/formType.ts
  src/types/index.ts
  tailwind.config.ts
Labels: ✨ Feat

#20 ✨ Feat: 로그인, 회원가입 페이지 UI 구현
  src/components/Auth/AuthContainer.tsx
  src/components/Auth/AuthInputWithLabel.tsx
  src/components/common/CommonButton.tsx
  src/constants/messages.tsx
  src/constants/regex.ts
  src/pages/login.tsx
  src/pages/signup.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feat

#9 ✨ Feat: 모달 컴포넌트 구현
  next.config.mjs
  package-lock.json
  package.json
  public/close.svg
  src/components/common/Modal.tsx
  src/hooks/index.ts
  src/hooks/useBoolean.ts
  src/pages/test.tsx
  tsconfig.json
Labels: ✨ Feat

#21 ✨ Feat: 헤더 컴포넌트 구현
  package-lock.json
  public/svg/hamburger.svg
  public/svg/notification.svg
  public/svg/profile.svg
  public/svg/wiki-viki-logo.svg
  src/components/common/Container.tsx
  src/components/common/Modal.tsx
  src/components/common/TopNavigationBar/HamburgerMenu.tsx
  src/components/common/TopNavigationBar/HamburgerMenuButtons.tsx
  src/components/common/TopNavigationBar/UserMenu.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/constants/storageKey.ts
  src/constants/windowSize.ts
  src/hooks/useIsLogin.ts
  src/hooks/useIsMobile.ts
  src/pages/_app.tsx
  src/pages/boards.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feat

#23 ✨ Feat: SearchBar 컴포넌트 구현
  package-lock.json
  public/svg/search.svg
  src/components/common/Modal 2.tsx
  src/components/common/SearchBar.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/pages/test3.tsx
  src/utils/debounce.ts
Labels: ✨ Feat

#30 🚑️ Fix: 잘못 merge된 부분 수정
  src/components/common/Modal 2.tsx
  src/pages/login.tsx
Labels: 🚑️ Fix

#24 ✨ Feat: Snackbar, LinkButton 컴포넌트 구현
  package-lock.json
  package.json
  public/lottie/check.json
  public/svg/check.svg
  public/svg/error.svg
  public/svg/info.svg
  public/svg/link.svg
  src/components/common/LinkButton.tsx
  src/components/common/ToastSelect.tsx
  src/pages/test3.tsx
  src/styles/ToastStyle.tsx
  src/types/toastOptions.ts
  src/utils/urlValidation.ts
Labels: ✨ Feat

#28 ✨내 위키 페이지 UI 구현
  next.config.mjs
  public/profileMockData.json
  public/svg/profile_expand_icon.svg
  src/components/Profiles/ProfileInfos.tsx
  src/components/Profiles/UserProfile.tsx
  src/components/common/Pagination.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/constants/url.ts
  src/pages/wiki/[code].tsx
  src/styles/globals.css
  src/types/UserProfileProps.ts
  tailwind.config.ts
Labels: ✨ Feat

#31 ✨ Feat: 자유게시판 페이지 UI 구현
  package-lock.json
  package.json
  public/data/boards.json
  public/image/empty-image.png
  src/components/FreeBoards/BoardCard.tsx
  src/components/FreeBoards/BoardCarousel.tsx
  src/components/FreeBoards/BoardList.tsx
  src/components/FreeBoards/DropDown.tsx
  src/components/FreeBoards/MobileBoardList.tsx
  src/components/FreeBoards/index.ts
  src/components/FreeBoards/style.module.css
  src/components/common/Pagination.tsx
  src/components/common/SearchBar.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/constants/orderOption.ts
  src/pages/boards.tsx
  src/types/board.ts
  src/utils/dateToString.ts
Labels: ✨ Feat

#34 ✨ Feat: wikilist 페이지 구현
  package-lock.json
  package.json
  public/data/wikilist.json
  public/image/nosearch-image.png
  public/lottie/nosearch.json
  src/components/WikiList/NoSearch.tsx
  src/components/WikiList/SearchLabel.tsx
  src/components/WikiList/UserCard.tsx
  src/components/WikiList/index.ts
  src/components/common/LinkButton.tsx
  src/constants/regex.ts
  src/pages/wikilist.tsx
  src/styles/globals.css
  src/types/UserCardProps.ts
  src/utils/searchRegex.ts
  src/utils/urlRegex.ts
  src/utils/urlValidation.ts
Labels: ✨ Feat

#36 ✨ Feat: linkbutton 기능 수정
  public/lottie/error.json
  src/components/WikiList/UserCard.tsx
  src/components/common/CopyLinkButton.tsx
  src/components/common/LinkButton.tsx
  src/components/common/ToastSelect.tsx
  src/pages/test3.tsx
  src/pages/wiki/[code].tsx
  src/pages/wikilist.tsx
Labels: ✨ Feat

#41 ✨ Feat: 기초 API 함수 작성
  .gitignore
  next.config.mjs
  public/images/basic_profile.png
  public/profileMockData.json
  public/quizMockData.json
  public/svg/locker_Icon.svg
  src/apis/index.ts
  src/components/Profiles/QuizModalTemplete.tsx
  src/components/Profiles/UserProfile.tsx
  src/constants/otherTypeErrorText.ts
  src/lib/apis/article/articleApi.api.ts
  src/lib/apis/axiosDefault.ts
  src/lib/apis/axiosWithIntercepter.ts
  src/lib/apis/comment/commentApi.api.ts
  src/lib/apis/image/imageApi.api.ts
  src/lib/apis/notification/notificationApi.api.ts
  src/lib/apis/profile/profileApi.api.ts
  src/lib/apis/user/userApi.api.ts
  src/pages/wiki/[code].tsx
  src/types/UserProfileProps.ts
  src/types/apiType.ts
Labels: ✨ Feat

#40 ✨ Feat: 위키 참여 인증 모달 스타일링
  next.config.mjs
  src/components/Profiles/QuizModalTemplete.tsx
  src/pages/wiki/[code].tsx
Labels: ✨ Feat

#48 ✨ Feat: 상단 네비게이션 바 수정
  public/data/notification.json
  public/svg/close.svg
  src/components/common/Modal.tsx
  src/components/common/TopNavigationBar/AuthUserMenu.tsx
  src/components/common/TopNavigationBar/HamburgerMenu.tsx
  src/components/common/TopNavigationBar/HamburgerMenuButtons.tsx
  src/components/common/TopNavigationBar/MenuContainer.tsx
  src/components/common/TopNavigationBar/MenuItem.tsx
  src/components/common/TopNavigationBar/NoticeItem.tsx
  src/components/common/TopNavigationBar/NoticeMenu.tsx
  src/components/common/TopNavigationBar/UserMenu.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/styles/globals.css
  src/types/apiType.ts
  src/utils/timeDiff.ts
Labels: ✨ Feat

#49 ✨ Feat: 계정 설정 페이지 api 연동
  .env
  src/components/Account/ChangePassWord.tsx
  src/components/Account/CreateWiki.tsx
  src/lib/axios.ts
Labels: ✨ Feat

#50 ✨ Feat: wikilist API 기능 구현 및 적용
  .env
  public/lottie/emptysearch.json
  src/components/WikiList/EmptySearch.tsx
  src/components/WikiList/NoSearch.tsx
  src/components/WikiList/SearchLabel.tsx
  src/components/WikiList/UserCard.tsx
  src/components/WikiList/index.ts
  src/components/common/CopyLinkButton.tsx
  src/constants/regex.ts
  src/lib/apis/profile/profileApi.api.ts
  src/lib/axios.ts
  src/pages/wikilist.tsx
  src/types/apiType.ts
  src/utils/urlRegex.ts
  src/utils/urlVaildation.ts
Labels: ✨ Feat

#58 ✨ Feat: toast message 동적 기능 구현
  .env
  public/lottie/error.json
  src/components/common/CopyLinkButton.tsx
  src/components/common/ToastSelect.tsx
  src/lib/apis/profile/profileApi.api.ts
  src/pages/boards.tsx
  src/pages/test3.tsx
  src/pages/wikilist.tsx
  src/types/toast.ts
  src/types/toastOptions.ts
Labels: ✨ Feat

#56 🚑️ Fix: 자유게시판 404 에러 해결
  src/pages/board/[boardId].tsx
Labels: 🚑️ Fix

#63 ✨ Feat: 404 custom error 페이지 구현
  public/lottie/404.json
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/_app.tsx
  src/pages/boards.tsx
  tailwind.config.ts
Labels: ✨ Feat

#57 ✨ Feat: 내 위키 페이지 수정 기능 구현
  next.config.mjs
  package-lock.json
  package.json
  public/profileMockData.json
  public/svg/camera_icon.svg
  src/components/Profiles/BasicWikiSection.tsx
  src/components/Profiles/Editor.tsx
  src/components/Profiles/ProfileInfos.tsx
  src/components/Profiles/QuizModalTemplete.tsx
  src/components/Profiles/UserProfile.tsx
  src/constants/editorBasicText.ts
  src/lib/apis/axiosWithIntercepter.ts
  src/pages/_app.tsx
  src/pages/wiki/[code].tsx
  src/styles/editor.css
  src/styles/globals.css
  src/types/UserProfileProps.ts
Labels: ✨ Feat

#61 🚑️ Fix: toast 커밋 오류 수정
  src/components/common/ToastSelect.tsx
  src/pages/test3.tsx
  src/types/toast.ts
Labels: 🚑️ Fix

#52 ✨ Feat: 로그인 여부 확인 및 로그아웃 구현
  package-lock.json
  package.json
  src/components/common/TopNavigationBar/AuthUserMenu.tsx
  src/components/common/TopNavigationBar/NoticeItem.tsx
  src/components/common/TopNavigationBar/NoticeMenu.tsx
  src/components/common/TopNavigationBar/UserMenu.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/hooks/useIsLogin.ts
  src/pages/boards.tsx
  src/pages/login.tsx
  src/store/userStore.ts
  src/utils/cookieUtil.ts
Labels: ✨ Feat

#70 🔨 Refactor: useAxiosFetch 훅 분리
  src/components/Account/ChangePassWord.tsx
  src/components/Account/CreateWiki.tsx
  src/hooks/useMutation.ts
  src/hooks/useQuery.ts
  src/lib/apis/Auth/changePasswordApi.ts
  src/lib/apis/Auth/createWikiApi.ts
  src/lib/apis/Auth/index.ts
  src/lib/apis/Auth/loginApi.ts
  src/lib/apis/Auth/signUpApi.ts
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: ✨ Feat

#67 ✨ Feat: 게시물 등록 페이지 UI 구현
  package-lock.json
  package.json
  src/components/AddBoard/ImageAddModal.tsx
  src/components/AddBoard/QuillEditor.tsx
  src/pages/addboard.tsx
  src/pages/test.tsx
  src/styles/addboard.css
  src/styles/globals.css
Labels: ✨ Feat
