Repository wiki-viki/wiki-viki, pull requests merged in 2024-07, with the labels that each got.

#73 ✨ Feat: zustand persist 적용
  src/components/common/TopNavigationBar/AuthUserMenu.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/pages/login.tsx
  src/pages/test.tsx
  src/store/useStore.ts
  src/store/userAuthStore.ts
  src/store/userStore.ts
Labels: ✨ Feat

#71 ✨ Feat: 내 위키 페이지 API 연동
  package-lock.json
  public/profileMockData.json
  public/quizMockData.json
  public/svg/spinner.svg
  src/components/Loading/index.tsx
  src/components/Profiles/Editor.tsx
  src/components/Profiles/ProfileInfos.tsx
  src/components/Profiles/QuizModalTemplete.tsx
  src/components/Profiles/UserProfile.tsx
  src/components/WikiList/UserCard.tsx
  src/constants/formDataInitialValue.ts
  src/lib/apis/axiosWithIntercepter.ts
  src/lib/apis/profile/profileApi.api.ts
  src/lib/apis/user/userApi.api.ts
  src/pages/_document.tsx
  src/pages/wiki/[code].tsx
  src/styles/editor.css
  src/styles/globals.css
  src/types/UserProfileProps.ts
  src/types/apiType.ts
Labels: ✨ Feat

#75 🔨 Refactor: 모달, 탑 네비게이션 컴포넌트 리팩토링
  src/components/common/Container.tsx
  src/components/common/Modal.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/styles/globals.css
Labels: 🔨 Refactor

#78 ✨ Feat: 게시물 등록하기 API 기능 구현
  src/components/AddBoard/ImageAddModal.tsx
  src/components/AddBoard/QuillEditor.tsx
  src/components/common/ToastSelect.tsx
  src/constants/imageUpload.ts
  src/pages/_app.tsx
  src/pages/addboard.tsx
  src/pages/test.tsx
  src/types/apiType.ts
  src/types/toast.ts
  src/utils/quillHtmlHandler.ts
Labels: ✨ Feat

#86 ✨ Feat: 랜딩 페이지 UI 구현
  public/image/LandingPage/Section2/content(1)-image.png
  public/image/LandingPage/Section2/cursor-image.png
  public/image/LandingPage/Section2/keyboard-image.png
  public/image/LandingPage/Section3/megaphone-image.png
  public/image/LandingPage/Section3/phone-image.png
  public/image/LandingPage/Section3/speech-bubble-image.png
  public/image/LandingPage/Section3/w-image.png
  public/image/LandingPage/Section4/bell-image.png
  public/image/LandingPage/Section4/content(2)-image.png
  public/image/LandingPage/Section4/content(3)-image.png
  src/components/Landing/AnimatedLogo.tsx
  src/components/Landing/CreateWikiSection.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/Header.tsx
  src/components/Landing/ShareSection.tsx
  src/components/Landing/SplashScreen.tsx
  src/components/Landing/ViewSection.tsx
  src/components/Landing/WriteSection.tsx
  src/components/Landing/index.ts
  src/components/common/Motion/RisingMotion.tsx
  src/components/common/Motion/index.ts
  src/hooks/useMutation.ts
  src/hooks/useQuery.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/store/userAuthStore.ts
  src/styles/globals.css
Labels: ✨ Feat

#85 ✨ Feat: 내 위키 페이지 수정 시 API 연동 및 기능 구현
  src/components/Loading/index.tsx
  src/components/Profiles/ProfileInfos.tsx
  src/components/Profiles/QuizModalTemplete.tsx
  src/components/Profiles/UserProfile.tsx
  src/components/common/TopNavigationBar/AuthUserMenu.tsx
  src/constants/formDataInitialValue.ts
  src/lib/apis/comment/commentApi.api.ts
  src/lib/apis/profile/profileApi.api.ts
  src/pages/wiki/[code].tsx
  src/store/userAuthStore.ts
  src/styles/editor.css
  src/styles/globals.css
  src/types/apiType.ts
  src/utils/throttle.ts
Labels: ✨ Feat

#80 ✨ Feat: 게시글 상세 페이지 구현
  package-lock.json
  package.json
  public/lottie/emptycomment.json
  public/svg/delete.svg
  public/svg/edit.svg
  public/svg/heart.svg
  public/svg/none-heart.svg
  src/components/BoardDetail/ArticleCard.tsx
  src/components/BoardDetail/ArticleComments.tsx
  src/components/BoardDetail/CommentCard.tsx
  src/components/BoardDetail/CommentCount.tsx
  src/components/BoardDetail/CommentEdit.tsx
  src/components/BoardDetail/CommentForm.tsx
  src/components/BoardDetail/index.ts
  src/components/common/ConfirmModal.tsx
  src/components/common/CopyLinkButton.tsx
  src/components/common/ToastSelect.tsx
  src/constants/toast.ts
  src/lib/apis/article/articleApi.api.ts
  src/lib/apis/comment/commentApi.api.ts
  src/pages/board/[boardId].tsx
  src/pages/test.tsx
  src/pages/test3.tsx
  src/styles/ToastStyle.tsx
  src/styles/globals.css
  src/types/apiType.ts
  src/types/boardDetail.ts
  src/types/toast.ts
Labels: ✨ Feat

#82 ✨ Feat: error page 디자인
  public/image/wikiviki-clover.png
  public/lottie/404.json
  src/components/FreeBoards/error/index.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/styles/error.mjs
  src/styles/globals.css
Labels: ✨ Feat

#95 🔨 Refactor: 게시물 작성하기 페이지 리팩토링
  package-lock.json
  package.json
  src/components/AddBoard/QuillEditor.tsx
  src/components/BoardDetail/ArticleComments.tsx
  src/components/BoardDetail/CommentEdit.tsx
Labels: 🔨 Refactor

#96 🔨 Refactor: 게시글 상세 페이지 리팩토링
  public/lottie/heart.json
  src/components/BoardDetail/ArticleCard.tsx
  src/components/BoardDetail/ArticleComments.tsx
  src/components/BoardDetail/CommentCard.tsx
  src/components/BoardDetail/CommentForm.tsx
  src/pages/board/[boardId].tsx
Labels: 🔨 Refactor

#98 🔨 Refactor: 위키목록 페이지 리팩토링
  src/components/BoardDetail/ArticleCard.tsx
  src/components/Profiles/UserProfile.tsx
  src/components/WikiList/SearchLabel.tsx
  src/components/WikiList/UserCard.tsx
  src/pages/wikilist.tsx
  src/styles/globals.css
Labels: 🔨 Refactor

#105 📦️ Chore: 이미지 색상 변경 및 500 에러 색상 변경
  public/image/empty-image.png
  public/images/basic_profile.png
  public/lottie/error.json
  public/svg/wiki-viki-logo.svg
  src/components/common/CustomError.tsx
  src/pages/board/[boardId]/edit.tsx
Labels: 📦️ Chore

#99 🔨 Refactor: 랜딩페이지 + 인증페이지 리팩토링
  docs/hyerin-check-list.md
  next.config.mjs
  public/image/LandingPage/Section2/cursor-image.png
  public/image/LandingPage/Section3/clover-image.png
  public/image/LandingPage/Section3/w-image.png
  public/image/LandingPage/Section4/content(3)-image.png
  src/components/Account/ChangePassWord.tsx
  src/components/Account/CreateWiki.tsx
  src/components/Landing/AnimatedLogo.tsx
  src/components/Landing/CreateWikiSection.tsx
  src/components/Landing/Footer.tsx
  src/components/Landing/Header.tsx
  src/components/Landing/ShareSection.tsx
  src/components/Landing/SplashScreen.tsx
  src/components/Landing/ViewSection.tsx
  src/components/Landing/WriteSection.tsx
  src/components/common/Form/Container.tsx
  src/components/common/TopNavigationBar/AuthUserMenu.tsx
  src/components/common/TopNavigationBar/MenuContainer.tsx
  src/components/common/TopNavigationBar/MenuItem.tsx
  src/components/index.ts
  src/hooks/useMutation.ts
  src/lib/apis/Auth/changePasswordApi.ts
  src/lib/apis/Auth/createWikiApi.ts
  src/lib/apis/Auth/index.ts
  src/lib/apis/Auth/loginApi.ts
  src/lib/apis/Auth/signUpApi.ts
  src/middleware.ts
  src/pages/_app.tsx
  src/pages/login.tsx
  src/pages/mypage.tsx
  src/pages/reset-password.tsx
  src/pages/signup.tsx
  src/store/userAuthStore.ts
  src/styles/globals.css
Labels: 🔨 Refactor

#103 ✨ Feat: 메타태그 설정
  public/image/wiki-viki-sm-logo.png
  src/components/BoardDetail/ArticleCard.tsx
  src/components/common/MetaTag.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/_document.tsx
  src/pages/addboard.tsx
  src/pages/board/[boardId]/edit.tsx
  src/pages/board/[boardId]/index.tsx
  src/pages/boards.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/mypage.tsx
  src/pages/reset-password.tsx
  src/pages/signup.tsx
  src/pages/wiki/[code].tsx
  src/pages/wikilist.tsx
Labels: ✨ Feat

#100 ✨ Feat: 알림창 기능 구현 및 페이지 리팩토링
  src/components/Landing/Header.tsx
  src/components/Profiles/UserProfile.tsx
  src/components/Profiles/UserProfile/EditProfile.tsx
  src/components/common/TopNavigationBar/NoticeItem.tsx
  src/components/common/TopNavigationBar/NoticeMenu.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/lib/apis/notification/notificationApi.api.ts
  src/pages/wiki/[code].tsx
  src/store/userAuthStore.ts
  src/styles/editor.css
Labels: ✨ Feat

#113 🔨 Refactor: 랜딩 페이지 리팩토링
  public/image/LandingPage/Section2/cursor-image.png
  src/components/Landing/Header.tsx
  src/pages/_app.tsx
Labels: 🔨 Refactor

#115 🚑️ Fix: 내 위키 및 알림창 버그 수정 및 알림창 렌더링 방식 변경
  src/components/Landing/Header.tsx
  src/components/Profiles/UserProfile/EditProfile.tsx
  src/components/common/TopNavigationBar/NoticeMenu.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/pages/wiki/[code].tsx
  src/styles/editor.css
Labels: 🚑️ Fix

#110 🚑️ Fix: 메타태그 오픈그래프 수정
  src/components/BoardDetail/ArticleCard.tsx
  src/components/common/MetaTag.tsx
  src/components/common/MetaTag/OpenGraphTag.tsx
  src/components/common/MetaTag/index.tsx
  src/pages/_document.tsx
  src/pages/addboard.tsx
  src/pages/board/[boardId]/edit.tsx
  src/pages/boards.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/mypage.tsx
  src/pages/reset-password.tsx
  src/pages/signup.tsx
  src/pages/wiki/[code].tsx
  src/pages/wikilist.tsx
Labels: 🚑️ Fix

#108 🚑️ Fix: 에러페이지 innerhtml 오류 수정, 게시글 상세 새고로침 오류 수정
  src/components/BoardDetail/ArticleComments.tsx
  src/components/WikiList/UserCard.tsx
  src/components/common/CopyLinkButton.tsx
  src/styles/error.mjs
Labels: 🚑️ Fix

#117 ✨ Feat: 로그아웃 확인 모달 구현 및 헤더 프로필 구현
  public/images/basic_profile.png
  src/components/common/TopNavigationBar/AuthUserMenu.tsx
  src/components/common/TopNavigationBar/MenuContainer.tsx
  src/components/common/TopNavigationBar/NoticeMenu.tsx
  src/components/common/TopNavigationBar/index.tsx
  src/middleware.ts
  src/pages/wiki/[code].tsx
  src/styles/addboard.css
Labels: ✨ Feat

#118 ✨ Feat: 페이지네이션 기능 및 취소 저장 모달 추가
  public/data/boards.json
  public/data/notification.json
  public/data/wikilist.json
  src/components/Profiles/QuizModalTemplete.tsx
  src/components/WikiList/UserCard.tsx
  src/components/common/Pagination.tsx
  src/constants/editorBasicText.ts
  src/constants/url.ts
  src/pages/test.tsx
  src/pages/test2.tsx
  src/pages/test3.tsx
  src/pages/wiki/[code].tsx
  src/store/userAuthStore.ts
  src/styles/addboard.css
Labels: ✨ Feat, 🔨 Refactor

#120 🚑️ Fix: toast css 변경 및 wikilist url 경로 수정(배포)
  src/components/WikiList/UserCard.tsx
  src/constants/url.ts
  src/pages/addboard.tsx
  src/pages/board/[boardId]/edit.tsx
  src/pages/boards.tsx
  src/pages/signup.tsx
  src/pages/wiki/[code].tsx
Labels: 🚑️ Fix

#122 🚑️ Fix: 특정 이름 표시 제한
  src/components/FreeBoards/BoardList.tsx
  src/components/FreeBoards/MobileBoardList.tsx
  src/components/WikiList/UserCard.tsx
Labels: 🚑️ Fix

#124 페이지 접근성 개선
  src/components/common/TopNavigationBar/index.tsx
  src/pages/_document.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: 📦️ Chore

#126 ✨ Feat: 로그인 하였을 시 베스트 게시글 좋아요 표시
  src/components/FreeBoards/BoardCard.tsx
  src/lib/apis/article/articleApi.api.ts
Labels: 🚑️ Fix, ✨ Feat

#127 📚 Docs: README.md 추가
  README.md
  public/images/wiki_viki_logo.png
  src/components/Profiles/Editor.tsx
Labels: 📦️ Chore
